// Mapa de iconos por nombre: el contenido guarda strings (serializables), y
// aquí se traducen a componentes de lucide. Así los datos de cada industria no
// dependen de React y el mismo nombre sirve en componentes servidor y cliente.
import {
  ArrowRight,
  BarChart3,
  BedDouble,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Building2,
  CalendarClock,
  Car,
  Check,
  ChevronDown,
  Clock,
  Dumbbell,
  FileText,
  GraduationCap,
  HeartHandshake,
  Image as ImageIcon,
  Layers,
  LifeBuoy,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  Package,
  PawPrint,
  PhoneCall,
  Plug,
  Repeat,
  ScanEye,
  Scissors,
  Search,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Store,
  Target,
  Ticket,
  TrendingUp,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  // industrias
  utensils: Utensils,
  stethoscope: Stethoscope,
  scissors: Scissors,
  building: Building2,
  car: Car,
  paw: PawPrint,
  dumbbell: Dumbbell,
  bed: BedDouble,
  graduation: GraduationCap,
  briefcase: Briefcase,
  // bloques de contenido
  message: MessageCircle,
  messages: MessagesSquare,
  phone: PhoneCall,
  calendar: CalendarClock,
  book: BookOpen,
  lead: UserPlus,
  ticket: Ticket,
  support: LifeBuoy,
  chart: BarChart3,
  insights: ScanEye,
  sparkles: Sparkles,
  shield: ShieldCheck,
  clock: Clock,
  users: Users,
  catalog: Package,
  shop: ShoppingBag,
  memory: Brain,
  bot: Bot,
  mic: Mic,
  image: ImageIcon,
  repeat: Repeat,
  target: Target,
  store: Store,
  zap: Zap,
  layers: Layers,
  file: FileText,
  handshake: HeartHandshake,
  trending: TrendingUp,
  search: Search,
  bell: Bell,
  campaign: Megaphone,
  wallet: Wallet,
  plug: Plug,
  check: Check,
  arrow: ArrowRight,
  chevron: ChevronDown,
};

export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Sparkles;
}
